#cloud-config
package_upgrade: true
timezone: "Europe/Oslo"
 
users:
  - name: administrator
    gecos: Lokal adminbruker 
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ADMINKEY
  - name: user
    gecos: Lokal bruker 
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - SSHKEY 
